#!/usr/bin/env python3
"""
STAGE 05 - emit static_transform_publisher commands.

Always emits the cameras that stage 04 produced. If "bag_anchor" is set it also
folds in stage 06's board anchors and SLAM bridges, so one script brings up the
whole tree in the correct parent order.

  python3 05_emit_tfs.py [pipeline_config.json]
  python3 05_emit_tfs.py pipeline_config.json > publish_tfs.sh
"""
import sys
import json
import numpy as np

from pipeline_common import load_pipeline, load_cameras_yaml, qR
from pipeline_boards import stp, T_from_record


def main():
    cfg_path = sys.argv[1] if len(sys.argv) > 1 else "pipeline_config.json"
    P = load_pipeline(cfg_path)
    s = P.stage("05_emit_tfs")

    blocks = []

    anchor = s.get("bag_anchor")
    if anchor:
        anchor = P.outp(anchor)
        try:
            ba = json.load(open(anchor))
        except (FileNotFoundError, OSError):
            print("# ! %s not found -- run 06_init_from_boards.py first" % anchor)
            ba = None
        if ba:
            for name, rec in sorted((ba.get("boards") or {}).items()):
                blocks.append(("board '%s'  (fixed anchor)" % name,
                               stp(rec["parent"], rec["child"], T_from_record(rec))))
            for name, rec in sorted((ba.get("bridges") or {}).items()):
                blocks.append(("SLAM bridge '%s'  (%s, %s views, std %s mm)"
                               % (name, rec.get("direction"), rec.get("n_views"),
                                  rec.get("std_mm")),
                               stp(rec["parent"], rec["child"], T_from_record(rec))))

    map_frame, cams = load_cameras_yaml(s["input"])
    for c in cams:
        parent = c.get("parent_frame", map_frame)
        T = np.eye(4)

        T[:3, :3] = qR(c["quaternion_xyzw"])
        T[:3, 3] = c["translation"]
        hdr = "camera %s  (source %s, stamp %s)" % (
            c["name"], c.get("source", "?"), c.get("stamp", "?"))
        if "raw_delta_cm" in c:
            hdr += "\n#   LiDAR-vs-ChArUco delta: %.1f cm / %.2f deg" % (
                c["raw_delta_cm"], c["raw_delta_deg"])
        if "spread_max_mm" in c:
            hdr += "\n#   board fit: %s detections, mean reproj %s px, scatter %s mm" % (
                c.get("n_detections"), c.get("mean_reproj_px"), c.get("spread_max_mm"))
        blocks.append((hdr, stp(parent, c["child_frame"], T)))

    print("#!/usr/bin/env bash")
    print("# generated by 05_emit_tfs.py -- parent order matters, see 06's header")
    print("set -e\n")
    for hdr, body in blocks:
        print("# %s" % hdr)
        print("%s &\n" % body.replace("  ros2", "ros2", 1))
    print("wait")


if __name__ == "__main__":
    main()
